{application,erlbook,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{erlbook,[]}},
              {env,[]},
              {modules,[afile_client,afile_server,geometry,helloworld,
                        math_functions,myfunc,mytupletolist]}]}.
