{application,erlbook,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{erlbook,[]}},
              {env,[]},
              {modules,[datetime,geometry,math_functions,myfunc,mytupletolist,
                        rfc4627]}]}.
